#!/usr/bin/env bash

link="$(zenity --entry --title='TikTokonvert' --text='TikTok Link:' --ok-label='Open' --cancel-label="Cancel")"

if [ $link ]; then

  videoid=$(echo $link | cut -d '/' -f 4-4)

  librewolf --new-instance --profile /home/qube/.librewolf/n6zrkvc0.proxitok https://proxitok.pussthecat.org/video/$videoid

else
  exit 0
fi
